In [1]:
# importing pandas as pd 
import pandas as pd 
  
# Making data frame from the csv file 
nome_empresa = "ACE"
empresas = pd.read_csv("Empresas.csv",encoding = "UTF-8" ,sep = ";")
socios = pd.read_csv("Socios.csv",encoding = "UTF-8",sep = ";")

empresas.columns

Index(['CNPJ', 'RAZAO', 'NOME FANTASIA', 'SITUACAO CADASTRAL', 'MATRIZ',
       'CNAE', 'DESCRICAO CNAE', 'CNAE2', 'DESCRICAO CNAE2', 'NATUREZA',
       'FATURAMENTO PRESUMIDO ANUAL', 'CAPITAL SOCIAL', 'PORTE', 'TITULO',
       'TIPO LOGRADOURO', 'LOGRADOURO', 'NUMERO', 'COMPLEMENTO', 'BAIRRO',
       'CIDADE', 'UF', 'CEP', 'EMAIL1', 'EMAIL1 VALIDO', 'EMAIL2',
       'EMAIL2 VALIDO', 'EMAIL3', 'EMAIL3 VALIDO', 'DDDFIXO1', 'FONEFIXO1',
       'DDDFIXO2', 'FONEFIXO2', 'DDDFIXO3', 'FONEFIXO3', 'DDDFIXO4',
       'FONEFIXO4', 'DDDMOVEL1', 'FONEMOVEL1', 'DDDMOVEL2', 'FONEMOVEL2',
       'DDDMOVEL3', 'FONEMOVEL3', 'DDDMOVEL4', 'FONEMOVEL4',
       'NATUREZA JURIDICA', 'PERSONA ATIVIDADE', 'DATA ABERTURA',
       'QUANTIDADE FUNCIONARIOS', 'QUANTIDADE SOCIOS', 'FLMOVELSOCIO',
       'SEGMENTO DIGITAL', 'WEB SITE', 'TIPO EMPRESA'],
      dtype='object')

In [2]:
caracteristicas_comuns_empresa_funcionario = {'DDDMOVEL1', 'FONEMOVEL1', 'DDDMOVEL2',
                                              'FONEMOVEL2', 'DDDMOVEL3', 'FONEMOVEL3', 'DDDMOVEL4', 'FONEMOVEL4',}
caracteristicas_inuteis_empresas = {'FATURAMENTO PRESUMIDO ANUAL','SITUACAO CADASTRAL', 'MATRIZ',
                                 'CNAE', 'DESCRICAO CNAE', 'CNAE2', 'DESCRICAO CNAE2', 'NATUREZA','CEP','EMAIL1 VALIDO',
                                 'EMAIL2', 'EMAIL2 VALIDO', 'EMAIL3', 'EMAIL3 VALIDO',
                                 'CAPITAL SOCIAL', 'PORTE', 'TITULO','QUANTIDADE FUNCIONARIOS', 'QUANTIDADE SOCIOS',
                                 'NATUREZA JURIDICA', 'PERSONA ATIVIDADE', 'DATA ABERTURA', 'FLMOVELSOCIO','TIPO EMPRESA',
                                 'SEGMENTO DIGITAL' }

In [3]:
empresas.drop(caracteristicas_comuns_empresa_funcionario,axis=1 ,inplace =True)

In [4]:
empresas.drop(caracteristicas_inuteis_empresas,axis=1 ,inplace =True)

In [5]:
empresas.columns

Index(['CNPJ', 'RAZAO', 'NOME FANTASIA', 'TIPO LOGRADOURO', 'LOGRADOURO',
       'NUMERO', 'COMPLEMENTO', 'BAIRRO', 'CIDADE', 'UF', 'EMAIL1', 'DDDFIXO1',
       'FONEFIXO1', 'DDDFIXO2', 'FONEFIXO2', 'DDDFIXO3', 'FONEFIXO3',
       'DDDFIXO4', 'FONEFIXO4', 'WEB SITE'],
      dtype='object')

In [6]:
df3 = []

for index, row in socios.iterrows():
    df3.append(empresas.loc[empresas.CNPJ == row.CNPJ])
    
df3 = pd.concat(df3)
df3

,CNPJ,RAZAO,NOME FANTASIA,TIPO LOGRADOURO,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,EMAIL1,DDDFIXO1,FONEFIXO1,DDDFIXO2,FONEFIXO2,DDDFIXO3,FONEFIXO3,DDDFIXO4,FONEFIXO4,WEB SITE
15,2225862000148,INOVA ACAO E RHESULTADO CONSULTORIA LTDA,INOVA ACAO E RHESULTADO,AVENIDA,CARLOS DE LIMA CAVALCANTE,3995.0,LOJA 27 CXPST 723,CASA CAIADA,OLINDA,PE,SOSGUIMARAES@UOL.COM.BR,81,34240273,81.0,32218902.0,81.0,34261279.0,81.0,34235461.0,NaN
84,5335946000122,DATAMETRICA AGROPECUARIA LTDA,DMA,RUA,DO BOM JESUS,220.0,ANDAR 2,RECIFE,RECIFE,PE,DMA@DATAMETRICA.COM.BR,81,32224350,81.0,39151039.0,81.0,37261162.0,81.0,39151006.0,http://datametrica.com.br/
4,7394410000103,J C CONTABILIDADE LTDA,JC CONTABILSOFT,RUA,DE INHAUMA,435.0,3 ANDAR,MAURICIO DE NASSAU,CARUARU,PE,NaN,81,37225434,81.0,31361115.0,NaN,NaN,NaN,NaN,NaN
30,9256457000136,VSF CONSULTORIA E SERVICOS EM SAUDE LTDA,NM SAUDE LTDA.,AVENIDA,GETULIO VARGAS,1038.0,LOJA 02 CXPST 33,BAIRRO NOVO,OLINDA,PE,NaN,81,21293550,87.0,38628858.0,87.0,38628881.0,87.0,38628896.0,http://nmsaude.com.br/
92,1843854000100,CONTAFISCO EIRELI,CONTAFISCO,AVENIDA,GETULIO VARGAS,930.0,SL 7 LJ 9 GA,BAIRRO NOVO,OLINDA,PE,CONTAFISCOADEMIR@IG.COM.BR,81,3429-8952,81.0,34292821.0,81.0,34298881.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,24753800000141,PRAXIS CONTABILIDADE LTDA,PRAXIS CONTABILIDADE,AVENIDA,REPUBLICA DO LIBANO,251.0,SL 906,PINA,RECIFE,PE,DIEGO@PRAXISBPO.COM.BR,81,30198080,81.0,34675499.0,NaN,NaN,NaN,NaN,http://praxisbpo.com.br/
80,18561915000131,BACK OFFICE SERVICOS ADMINISTRATIVOS LTDA,BACK OFFICE ADMINISTRATIVOS,RODOVIA,BR-101 NORTE,5740.0,SALA 03,ARTUR LUNDGREN II,PAULISTA,PE,TRIBUTOSDIRETOS@YESCOSMETICS.COM.BR,81,21232819,81.0,21232800.0,NaN,NaN,NaN,NaN,NaN
71,35521046000130,TGI - CONSULTORIA EM GESTAO EMPRESARIAL LTDA,TGI - CONSULTORIA EM GESTAO S/A,RUA,DE ITAMARACA,293.0,NaN,ESPINHEIRO,RECIFE,PE,TGI@TGI.COM.BR,21,35795829,81.0,30312533.0,81.0,31341734.0,81.0,31341742.0,http://tgi.com.br/
84,5335946000122,DATAMETRICA AGROPECUARIA LTDA,DMA,RUA,DO BOM JESUS,220.0,ANDAR 2,RECIFE,RECIFE,PE,DMA@DATAMETRICA.COM.BR,81,32224350,81.0,39151039.0,81.0,37261162.0,81.0,39151006.0,http://datametrica.com.br/
71,35521046000130,TGI - CONSULTORIA EM GESTAO EMPRESARIAL LTDA,TGI - CONSULTORIA EM GESTAO S/A,RUA,DE ITAMARACA,293.0,NaN,ESPINHEIRO,RECIFE,PE,TGI@TGI.COM.BR,21,35795829,81.0,30312533.0,81.0,31341734.0,81.0,31341742.0,http://tgi.com.br/

In [7]:
df = pd.concat([df3.reset_index(drop=True), socios], axis=1)

In [8]:
df = df.loc[:,~df.columns.duplicated()]

In [9]:
df.columns

Index(['CNPJ', 'RAZAO', 'NOME FANTASIA', 'TIPO LOGRADOURO', 'LOGRADOURO',
       'NUMERO', 'COMPLEMENTO', 'BAIRRO', 'CIDADE', 'UF', 'EMAIL1', 'DDDFIXO1',
       'FONEFIXO1', 'DDDFIXO2', 'FONEFIXO2', 'DDDFIXO3', 'FONEFIXO3',
       'DDDFIXO4', 'FONEFIXO4', 'WEB SITE', 'NOME', 'DDDMOVEL1', 'FONEMOVEL1',
       'DDDMOVEL2', 'FONEMOVEL2', 'DDDMOVEL3', 'FONEMOVEL3', 'DDDMOVEL4',
       'FONEMOVEL4', 'EMAIL CORPORATIVO', 'EMAIL VALIDADO'],
      dtype='object')

In [10]:
df.head()

,CNPJ,RAZAO,NOME FANTASIA,TIPO LOGRADOURO,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,...,DDDMOVEL1,FONEMOVEL1,DDDMOVEL2,FONEMOVEL2,DDDMOVEL3,FONEMOVEL3,DDDMOVEL4,FONEMOVEL4,EMAIL CORPORATIVO,EMAIL VALIDADO
0,2225862000148,INOVA ACAO E RHESULTADO CONSULTORIA LTDA,INOVA ACAO E RHESULTADO,AVENIDA,CARLOS DE LIMA CAVALCANTE,3995.0,LOJA 27 CXPST 723,CASA CAIADA,OLINDA,PE,...,81.0,988083677.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5335946000122,DATAMETRICA AGROPECUARIA LTDA,DMA,RUA,DO BOM JESUS,220.0,ANDAR 2,RECIFE,RECIFE,PE,...,81.0,992329476.0,NaN,NaN,NaN,NaN,NaN,NaN,analice.amazonas@datametrica.com.br,S
2,7394410000103,J C CONTABILIDADE LTDA,JC CONTABILSOFT,RUA,DE INHAUMA,435.0,3 ANDAR,MAURICIO DE NASSAU,CARUARU,PE,...,81.0,988313168.0,81.0,989350114.0,81.0,996640038.0,81.0,981372254.0,NaN,NaN
3,9256457000136,VSF CONSULTORIA E SERVICOS EM SAUDE LTDA,NM SAUDE LTDA.,AVENIDA,GETULIO VARGAS,1038.0,LOJA 02 CXPST 33,BAIRRO NOVO,OLINDA,PE,...,81.0,984324330.0,81.0,991862043.0,NaN,NaN,NaN,NaN,marcelo.alves@nmsaude.com.br,N
4,1843854000100,CONTAFISCO EIRELI,CONTAFISCO,AVENIDA,GETULIO VARGAS,930.0,SL 7 LJ 9 GA,BAIRRO NOVO,OLINDA,PE,...,66.0,992095182.0,87.0,988038413.0,65.0,993523497.0,81.0,986040920.0,NaN,NaN

In [11]:
#Convertendo o Cnpj para o formato certo
df['CNPJ'] = df['CNPJ'].astype('str')

In [12]:
#Formatando o padrao
def montaCnpj(cnpj):
    cnpjFormatado = '{}.{}.{}/{}-{}'.format(cnpj[:2], cnpj[2:5], cnpj[5:8], cnpj[8:12],cnpj[12:])
    return cnpjFormatado

In [13]:
df['CNPJ'] = df.apply(lambda x: montaCnpj(x['CNPJ']), axis = 1)

In [14]:
df['OBSERVACAO 1'] = ""
df['OBSERVACAO 2'] = ""

Defindindo funcao para converter o telefone para o formato padrao (DDD)numero

In [15]:
def montaTelefone(ddd,telefone):
    return ("(" + str(ddd) + ")" + str(telefone))

In [16]:
#Preechendo campos nulos de telefone fixo:
df['DDDFIXO1'].fillna(0,inplace = True)
df['DDDFIXO2'].fillna(0,inplace = True)
df['DDDFIXO3'].fillna(0,inplace = True)
df['DDDFIXO4'].fillna(0,inplace = True)


df['FONEFIXO1'].fillna(0,inplace = True)
df['FONEFIXO2'].fillna(0,inplace = True)
df['FONEFIXO3'].fillna(0,inplace = True)
df['FONEFIXO4'].fillna(0,inplace = True)

In [17]:
#Preechendo campos nulos de telefone celular:
df['DDDMOVEL1'].fillna(0,inplace = True)
df['DDDMOVEL2'].fillna(0,inplace = True)
df['DDDMOVEL3'].fillna(0,inplace = True)
df['DDDMOVEL4'].fillna(0,inplace = True)


df['FONEMOVEL1'].fillna(0,inplace = True)
df['FONEMOVEL2'].fillna(0,inplace = True)
df['FONEMOVEL3'].fillna(0,inplace = True)
df['FONEMOVEL4'].fillna(0,inplace = True)

Convertendo o telefone fixo para o formato padrao (DDD)numero

In [18]:
df['TELEFONE FIXO DA EMPRESA 1'] = df.apply(lambda x: montaTelefone(int(x['DDDFIXO1']),x['FONEFIXO1']), axis = 1)

In [19]:
df['TELEFONE FIXO DA EMPRESA 2'] = df.apply(lambda x: montaTelefone(int(x['DDDFIXO2']),int(x['FONEFIXO2'])), axis = 1)

In [20]:
df['TELEFONE FIXO DA EMPRESA 3'] = df.apply(lambda x: montaTelefone(int(x['DDDFIXO3']),int(x['FONEFIXO3'])), axis = 1)

In [21]:
df['TELEFONE FIXO DA EMPRESA 4'] = df.apply(lambda x: montaTelefone(int(x['DDDFIXO4']),int(x['FONEFIXO4'])), axis = 1)

In [22]:
df.head()

,CNPJ,RAZAO,NOME FANTASIA,TIPO LOGRADOURO,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,UF,...,DDDMOVEL4,FONEMOVEL4,EMAIL CORPORATIVO,EMAIL VALIDADO,OBSERVACAO 1,OBSERVACAO 2,TELEFONE FIXO DA EMPRESA 1,TELEFONE FIXO DA EMPRESA 2,TELEFONE FIXO DA EMPRESA 3,TELEFONE FIXO DA EMPRESA 4
0,22.258.620/0014-8,INOVA ACAO E RHESULTADO CONSULTORIA LTDA,INOVA ACAO E RHESULTADO,AVENIDA,CARLOS DE LIMA CAVALCANTE,3995.0,LOJA 27 CXPST 723,CASA CAIADA,OLINDA,PE,...,0.0,0.0,NaN,NaN,,,(81)34240273,(81)32218902,(81)34261279,(81)34235461
1,53.359.460/0012-2,DATAMETRICA AGROPECUARIA LTDA,DMA,RUA,DO BOM JESUS,220.0,ANDAR 2,RECIFE,RECIFE,PE,...,0.0,0.0,analice.amazonas@datametrica.com.br,S,,,(81)32224350,(81)39151039,(81)37261162,(81)39151006
2,73.944.100/0010-3,J C CONTABILIDADE LTDA,JC CONTABILSOFT,RUA,DE INHAUMA,435.0,3 ANDAR,MAURICIO DE NASSAU,CARUARU,PE,...,81.0,981372254.0,NaN,NaN,,,(81)37225434,(81)31361115,(0)0,(0)0
3,92.564.570/0013-6,VSF CONSULTORIA E SERVICOS EM SAUDE LTDA,NM SAUDE LTDA.,AVENIDA,GETULIO VARGAS,1038.0,LOJA 02 CXPST 33,BAIRRO NOVO,OLINDA,PE,...,0.0,0.0,marcelo.alves@nmsaude.com.br,N,,,(81)21293550,(87)38628858,(87)38628881,(87)38628896
4,18.438.540/0010-0,CONTAFISCO EIRELI,CONTAFISCO,AVENIDA,GETULIO VARGAS,930.0,SL 7 LJ 9 GA,BAIRRO NOVO,OLINDA,PE,...,81.0,986040920.0,NaN,NaN,,,(81)3429-8952,(81)34292821,(81)34298881,(0)0

In [23]:
info_telefone_picado = {'DDDFIXO1', 'FONEFIXO1','DDDFIXO2', 'FONEFIXO2', 'DDDFIXO3', 'FONEFIXO3','DDDFIXO4','FONEFIXO4'}

In [24]:
df.drop(info_telefone_picado,axis = 1 , inplace = True)

Convertendo o telefone celular para o formato padrao (DDD)numero

In [25]:
df['TELEFONE CELULAR DO DECISOR 1'] = df.apply(lambda x: montaTelefone(int(x['DDDMOVEL1']),int(x['FONEMOVEL1'])), axis = 1)

In [26]:
df['TELEFONE CELULAR DO DECISOR 2'] = df.apply(lambda x: montaTelefone(int(x['DDDMOVEL2']),int(x['FONEMOVEL2'])), axis = 1)

In [27]:
df['TELEFONE CELULAR DO DECISOR 3'] = df.apply(lambda x: montaTelefone(int(x['DDDMOVEL3']),int(x['FONEMOVEL3'])), axis = 1)

In [28]:
df['TELEFONE CELULAR DO DECISOR 4'] = df.apply(lambda x: montaTelefone(int(x['DDDMOVEL4']),int(x['FONEMOVEL4'])), axis = 1)

In [29]:
info_telefone_movel_picado = {'DDDMOVEL1','FONEMOVEL1','DDDMOVEL2','FONEMOVEL2','DDDMOVEL3','FONEMOVEL3','DDDMOVEL4','FONEMOVEL4'}

In [30]:
df.drop(info_telefone_movel_picado,axis = 1, inplace =True)

In [31]:
def montaEndereco(tipo,logradouro):
    return (str(tipo) + " " + str(logradouro))

In [32]:
df['NUMERO'].fillna(-11, inplace = True)
df['NUMERO1'] = df['NUMERO'].astype(int)
df['NUMERO1'].replace(-11, "Sem Numero", inplace = True)
df['NUMERO'] = df['NUMERO1']

In [33]:
df['ENDERECO'] = df.apply(lambda x: montaEndereco(x['TIPO LOGRADOURO'], x['LOGRADOURO'] ), axis =1)

In [34]:
lista_endereco = {'NUMERO1', 'TIPO LOGRADOURO' , 'LOGRADOURO'}

df.drop(lista_endereco , axis = 1, inplace = True)

In [35]:
#Mudando nomes de variaveis 
df['NOME DO DECISOR'] = df['NOME']
df['RAZAO SOCIAL'] = df['RAZAO']
df['EMAIL CADASTRADO NA RECEITA'] = df['EMAIL1']
df['EMAIL CORPORATIVO DO DECISOR'] = df['EMAIL CORPORATIVO']

lista_remover_trocados ={'NOME','EMAIL1','EMAIL CORPORATIVO','RAZAO'}
df.drop(lista_remover_trocados,axis = 1, inplace =True)

In [36]:
#passando variaveis para minusculo
df['RAZAO SOCIAL'] = df['RAZAO SOCIAL'].str.title()
df['NOME FANTASIA'] = df['NOME FANTASIA'].str.title()

#df['TIPO LOGRADOURO'] = df['TIPO LOGRADOURO'].str.title()
#df['LOGRADOURO'] = df['LOGRADOURO'].str.title()
df['ENDERECO'] = df['ENDERECO'].str.title()

df['COMPLEMENTO'] = df['COMPLEMENTO'].str.title()
df['BAIRRO'] = df['BAIRRO'].str.title()


df['CIDADE'] = df['CIDADE'].str.title()
df['NOME DO DECISOR'] = df['NOME DO DECISOR'].str.title()

df['EMAIL CADASTRADO NA RECEITA'] = df['EMAIL CADASTRADO NA RECEITA'].str.lower()

In [37]:
df1 = df[['CNPJ', 'RAZAO SOCIAL', 'NOME FANTASIA',
       'ENDERECO', 'NUMERO', 'COMPLEMENTO', 'BAIRRO',
       'CIDADE', 'UF', 'WEB SITE','NOME DO DECISOR','TELEFONE FIXO DA EMPRESA 1',
       'TELEFONE FIXO DA EMPRESA 2', 'TELEFONE FIXO DA EMPRESA 3',
       'TELEFONE FIXO DA EMPRESA 4', 'TELEFONE CELULAR DO DECISOR 1',
       'TELEFONE CELULAR DO DECISOR 2', 'TELEFONE CELULAR DO DECISOR 3',
       'TELEFONE CELULAR DO DECISOR 4','EMAIL CORPORATIVO DO DECISOR','EMAIL CADASTRADO NA RECEITA','OBSERVACAO 1',
       'OBSERVACAO 2']]
df1.replace('(0)0','-',inplace = True)
#df1.to_csv(nome_empresa + "Modelo Planilha.csv", sep = ';')
df1.to_csv("leads_" + nome_empresa + " socios" + ".csv", sep = ';')

/Users/yurimoreira/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,